### ISSUE TITLE
Updated to Ember 2.13+ and got this error

### ISSUE THREAD

**Issue by robclancy** [toranb/ember-template-compiler#34]
Not 100% sure if this is the right place to report this. And if it is better in latest versions (when I finish updating to latest I'll put the bad template back in and see what error it gives).

EDIT: same thing in ember 2.17.0-beta.1

I am upgrading one version at a time from 2.12. I had an issue with a bad template. The issue here is the error gave absolutely no indication of what was wrong. I found it by deleting one template after another until the error went away. Then I spotted this...

`disabled={{true}}` on a button.

Here is the error I got:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (preprocessedApp & templates)] failed with:
TypeError: Cannot read property 'length' of undefined
    at Object._isMulipartPath (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:14898:24)
    at Object._isInlineInvocation (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:14901:16)
    at MustacheStatement (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:14924:21)
    at visitNode (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2404:36)
    at visitKey (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2444:23)
    at visitNode (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2419:17)
    at visitArray (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2461:22)
    at visitKey (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2442:13)
    at visitNode (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2419:17)
    at visitArray (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2461:22)
    at visitKey (/home/robbo/projects/postedin/marketplace/node_modules/ember-source/dist/ember-template-compiler.js:2442:13)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/home/robbo/projects/postedin/marketplace/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at EmberApp._mergeTrees (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/ember-app.js:1815:12)
    at EmberApp.appAndDependencies (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/ember-app.js:1111:51)
    at EmberApp.javascript (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/ember-app.js:1235:30)
    at EmberApp.toArray (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/ember-app.js:1672:12)
    at EmberApp.toTree (/home/robbo/projects/postedin/marketplace/node_modules/ember-cli/lib/broccoli/ember-app.js:1694:38)
    at module.exports (/home/robbo/projects/postedin/marketplace/ember-cli-build.js:116:14)
```

**Comment by toranb** [comment]
Sorry to break the news :( but this project isn't updated/or used anymore. The issue(s) you are facing with the upgrade from 2.12 is that in 2.13 ember took a new glimmer VM v0.22 if I recall correctly. You should likely open an issue with ember itself to file a bug/or reproduce via ember twiddle

**Comment by robclancy** [comment]
Ah okay, I was following the last error I got to try find the correct repository. 

Edit: and now reading the description of this repository I realize I'm an idiot haha.
